# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Разрешаем выполнять shell-команды
shell_command:
  pull_and_restart: 'bash /config/update-ha.sh && ha core restart'

# Подключаем автоматизации из папки
automation: !include_dir_merge_list automations/

script: !include scripts.yaml
scene: !include scenes.yaml

# Yandex Smart Home integration
yandex_smart_home: !include yandex_smart_home.yaml
