alias: "Статус интернета"
trigger:
  - platform: conversation
    command: ["интернет работает", "статус интернета"]
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.yandex_station
    data:
      media_content_id: "{{ 'Интернет работает' if states('sensor.archer_a5_wan_status') == 'connected' else 'Интернет не работает' }}"
      media_content_type: "text"